   //01234567890123456789
var openingText = [
    "For many eons,",
    "the Empire has",
    "flourished under",
    "the leadership of",
    "the god-empress,",
    "Princess Mary.",
    "",
    "Together with her",
    "partner Nicole, she",
    "created a new era",
    "of peace and",
    "prosperity.",
    "",
    "But like all",
    "good things,",
    "this too must come", 
    "to an end..."
    ];

var creditsText = [
    "Aspect Star III",
    "Credits",
    "",
    "",
    "",
    "",
    "DEVELOPER",
    "Nicole Express",
    "",
    "",
    "PROGRAMMING",
    "Nicole Express",
    "",
    "",
    "GAME DESIGN",
    "Nicole Express",
    "",
    "",
    "GRAPHICS",
    "Nicole Express",
    "",
    "",
    "MUSIC AND SOUND",
    "Nicole Express",
    "",
    "",
    "SPECIAL THANKS TO",
    "howler.js",
    "DefleMask",
    "Aspect Star 1 Team",
    "Aspect Star 2 Team",
    "and of course,",
    "Marion",
    "",
    "",
    "",
    "",
    "A Nicole",
    "Production",
    "",
    "Thanks for playing!",
    "",
]