   //01234567890123456789
var openingText = [
    "For many years,",
    "the Empire has",
    "flourished under",
    "the leadership of",
    "the god-empress,",
    "Princess Mary.",
    "",
    "Together with her",
    "consort Nicole, she",
    "created a new era",
    "of peace and",
    "prosperity.",
    "",
    "But any system",
    "built on a single",
    "person has a",
    "key flaw...",
    ];

var creditsText = [
    "Aspect Star 3",
    "Credits",
    "",
    "",
    "",
    "",
    "DEVELOPER",
    "Nicole Express",
    "",
    "",
    "PROGRAMMING",
    "Nicole Express",
    "",
    "",
    "GAME DESIGN",
    "Nicole Express",
    "",
    "",
    "GRAPHICS",
    "Nicole Express",
    "",
    "",
    "MUSIC AND SOUND",
    "Nicole Express",
    "",
    "",
    "SPECIAL THANKS TO",
    "Marion",
    "Aspect Star 1 Team",
    "Aspect Star 2 Team",
    "",
    "",
    "",
    "",
    "A Nicole",
    "Production",
    "",
    "Thanks for playing!",
    "",
]